why is it anonymous? if not for rigging...

if there is only one vote against the majority, it would be easy to find out who it was if they were willing to share the information, and they alone shared the information; they would if they didn't feel threatened, and had a good reason
